id: AA5FC96E1
title: 'Victory Over All Adversity: A Prayer to Invoke Guru Rinpoche’s Wisdom for
  the Swift Fulfilment of Wishes'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:19:23.413979
  last_modified_at: 2022-03-01 01:19:23.413982
