id: AA5FC96E1
title: An Extremely Concise Barché Lamsel—The Prayer for Clearing Obstacles from the
  Path
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:19:23.407747
  last_modified_at: 2022-03-01 01:19:23.407753
