id: AA5FC96E1
title: The Seven Lines that Dispel All Obstacles and Enfold All Profundity
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:19:23.410743
  last_modified_at: 2022-03-01 01:19:23.410746
