id: AA5FC96E1
title: 'The Spontaneous Fulfilment of All Wishes: Invoking the Great Guru of Uḍḍiyāna'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:19:23.412066
  last_modified_at: 2022-03-01 01:19:23.412070
