id: AA5FC96E1
title: An Extremely Concise Sampa Lhundrup—Prayer that Spontaneously Fulfils All Wishes
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:19:23.409289
  last_modified_at: 2022-03-01 01:19:23.409293
